import os
import sys
import textwrap
from PIL import Image, ImageDraw, ImageFont

class DisplayHandler:
    def __init__(self, picdir):
        self.epd = None
        self.picdir = picdir
        self.font = None
        self.status_font = None
        self.title_font = None
        self.width = 400
        self.height = 300
        
        self._init_epd()
        self._load_fonts()
        
    def _init_epd(self):
        try:
            from waveshare_epd import epd4in2_V2
            self.epd = epd4in2_V2.EPD()
            self.width = self.epd.width
            self.height = self.epd.height
            
            print("Initializing display...")
            self.epd.init()
            self.epd.Clear()
            self.epd.init_fast(self.epd.Seconds_1_5S)
        except Exception as e:
            print(f"Display Init Failed (running in headless fallback mode): {e}")

    def _load_fonts(self):
        try:
            self.font = ImageFont.truetype(os.path.join(self.picdir, 'Font.ttc'), 18)
            self.status_font = ImageFont.truetype(os.path.join(self.picdir, 'Font.ttc'), 12)
            self.title_font = ImageFont.truetype(os.path.join(self.picdir, 'Font.ttc'), 24)
        except IOError:
            print("Fonts not found, falling back to default fonts.")
            self.font = ImageFont.load_default()
            self.status_font = ImageFont.load_default()
            self.title_font = ImageFont.load_default()

    def render_menu(self, menu_items, selected_idx):
        img = Image.new('1', (self.width, self.height), 255)
        draw = ImageDraw.Draw(img)
        
        draw.text((10, 10), "--- ZEROWRITER ---", font=self.title_font, fill=0)
        y = 50
        visible_items = menu_items[:8]
        for idx, item in enumerate(visible_items):
            prefix = "> " if idx == selected_idx else "  "
            draw.text((10, y), f"{prefix}{item}", font=self.font, fill=0)
            y += 24
            
        draw.line((0, 275, self.width, 275), fill=0)
        draw.text((10, 280), "Use Arrow keys. Enter to Open.", font=self.status_font, fill=0)
        self.update(img)

    def render_recovery(self):
        img = Image.new('1', (self.width, self.height), 255)
        draw = ImageDraw.Draw(img)
        
        draw.text((10, 10), "--- CRASH RECOVERY ---", font=self.title_font, fill=0)
        draw.text((10, 60), "An unsaved draft was found.", font=self.font, fill=0)
        draw.text((10, 90), "Would you like to recover it?", font=self.font, fill=0)
        draw.text((10, 140), "Press [Y] to Recover and Edit", font=self.font, fill=0)
        draw.text((10, 170), "Press [N] to Discard and Start New", font=self.font, fill=0)
        
        draw.line((0, 275, self.width, 275), fill=0)
        draw.text((10, 280), "Unsaved changes detected", font=self.status_font, fill=0)
        self.update(img)

    def render_new_file(self, filename_buffer):
        img = Image.new('1', (self.width, self.height), 255)
        draw = ImageDraw.Draw(img)
        
        draw.text((10, 10), "--- NEW DOCUMENT ---", font=self.title_font, fill=0)
        draw.text((10, 60), "Enter filename:", font=self.font, fill=0)
        draw.rectangle((10, 90, 390, 120), outline=0)
        draw.text((15, 95), filename_buffer + "_", font=self.font, fill=0)
        
        draw.text((10, 140), "Press Enter to create.", font=self.status_font, fill=0)
        draw.text((10, 160), "Leave empty for autogenerated name.", font=self.status_font, fill=0)
        self.update(img)

    def render_editor(self, text, sync_indicator):
        img = Image.new('1', (self.width, self.height), 255)
        draw = ImageDraw.Draw(img)
        
        # Word wrap text
        lines_to_render = []
        for paragraph in text.split('\n'):
            wrapped = textwrap.wrap(paragraph, width=35)
            if not wrapped:
                lines_to_render.append("")
            else:
                lines_to_render.extend(wrapped)
                
        y = 10
        for line in lines_to_render[-11:]:
            draw.text((10, y), line, font=self.font, fill=0)
            y += 24
            
        # Status bar
        draw.line((0, 275, self.width, 275), fill=0)
        words_count = len(text.split())
        status_text = f"Ctrl+Q: Menu | Ctrl+S: Save ({sync_indicator}) | Words: {words_count}"
        draw.text((10, 280), status_text, font=self.status_font, fill=0)
        self.update(img)

    def update(self, img, full_refresh=False):
        if not self.epd:
            return
        try:
            if full_refresh:
                self.epd.init()
                self.epd.display(self.epd.getbuffer(img))
                self.epd.init_fast(self.epd.Seconds_1_5S)
            else:
                self.epd.display_Partial(self.epd.getbuffer(img))
        except Exception as e:
            print(f"Error updating display: {e}")

    def shutdown(self):
        if not self.epd:
            return
        print("Clearing display and putting it to sleep...")
        try:
            self.epd.init()
            self.epd.Clear()
            self.epd.sleep()
        except Exception as e:
            print(f"Error shutting down display: {e}")
