import os
import sys
import textwrap
from PIL import Image, ImageDraw, ImageFont
from zerowriter import config

class DisplayHandler:
    def __init__(self, picdir):
        self.epd = None
        self.picdir = picdir
        self.font = None
        self.status_font = None
        self.title_font = None
        self.width = 400
        self.height = 300
        
        self._init_epd()
        self._load_fonts()
        
    def _init_epd(self):
        try:
            from waveshare_epd import epd4in2_V2
            self.epd = epd4in2_V2.EPD()
            self.width = self.epd.width
            self.height = self.epd.height
            
            print("Initializing display...")
            self.epd.init()
            self.epd.Clear()
            self.epd.init_fast(self.epd.Seconds_1_5S)
        except Exception as e:
            print(f"Display Init Failed (running in headless fallback mode): {e}")

    def _load_fonts(self):
        try:
            self.font = ImageFont.truetype(os.path.join(self.picdir, 'Font.ttc'), 18)
            self.status_font = ImageFont.truetype(os.path.join(self.picdir, 'Font.ttc'), 12)
            self.title_font = ImageFont.truetype(os.path.join(self.picdir, 'Font.ttc'), 24)
        except IOError:
            print("Fonts not found, falling back to default fonts.")
            self.font = ImageFont.load_default()
            self.status_font = ImageFont.load_default()
            self.title_font = ImageFont.load_default()

    def render_menu(self, menu_items, selected_idx):
        img = Image.new('1', (self.width, self.height), 255)
        draw = ImageDraw.Draw(img)
        
        draw.text((10, 10), "--- ZEROWRITER ---", font=self.title_font, fill=0)
        y = 50
        visible_items = menu_items[:8]
        for idx, item in enumerate(visible_items):
            prefix = "> " if idx == selected_idx else "  "
            draw.text((10, y), f"{prefix}{item}", font=self.font, fill=0)
            y += 24
            
        draw.line((0, 275, self.width, 275), fill=0)
        draw.text((10, 280), "Use Arrow keys. Enter to Open.", font=self.status_font, fill=0)
        self.update(img)

    def render_recovery(self):
        img = Image.new('1', (self.width, self.height), 255)
        draw = ImageDraw.Draw(img)
        
        draw.text((10, 10), "--- CRASH RECOVERY ---", font=self.title_font, fill=0)
        draw.text((10, 60), "An unsaved draft was found.", font=self.font, fill=0)
        draw.text((10, 90), "Would you like to recover it?", font=self.font, fill=0)
        draw.text((10, 140), "Press [Y] to Recover and Edit", font=self.font, fill=0)
        draw.text((10, 170), "Press [N] to Discard and Start New", font=self.font, fill=0)
        
        draw.line((0, 275, self.width, 275), fill=0)
        draw.text((10, 280), "Unsaved changes detected", font=self.status_font, fill=0)
        self.update(img)

    def render_new_file(self, filename_buffer):
        img = Image.new('1', (self.width, self.height), 255)
        draw = ImageDraw.Draw(img)
        
        draw.text((10, 10), "--- NEW DOCUMENT ---", font=self.title_font, fill=0)
        draw.text((10, 60), "Enter filename:", font=self.font, fill=0)
        draw.rectangle((10, 90, 390, 120), outline=0)
        draw.text((15, 95), filename_buffer + "_", font=self.font, fill=0)
        
        draw.text((10, 140), "Press Enter to create.", font=self.status_font, fill=0)
        draw.text((10, 160), "Leave empty for autogenerated name.", font=self.status_font, fill=0)
        self.update(img)

    def render_keyboard_error(self):
        img = Image.new('1', (self.width, self.height), 255)
        draw = ImageDraw.Draw(img)
        
        draw.text((10, 10), "--- KEYBOARD ERROR ---", font=self.title_font, fill=0)
        draw.text((10, 70), "Please connect a USB keyboard.", font=self.font, fill=0)
        draw.text((10, 110), "The system is waiting...", font=self.font, fill=0)
        draw.text((10, 160), "Your typing progress is safe in memory.", font=self.status_font, fill=0)
        
        draw.line((0, 275, self.width, 275), fill=0)
        draw.text((10, 280), "Scanning for keyboard...", font=self.status_font, fill=0)
        self.update(img)

    def _wrap_text_pixels(self, text, font, max_width):
        def get_width(t):
            if hasattr(font, 'getlength'):
                return font.getlength(t)
            elif hasattr(font, 'getbbox'):
                return font.getbbox(t)[2] - font.getbbox(t)[0]
            else:
                return font.getsize(t)[0]

        lines = []
        for paragraph in text.split('\n'):
            if not paragraph:
                lines.append("")
                continue
                
            words = paragraph.split(' ')
            current_line = []
            for word in words:
                test_line = ' '.join(current_line + [word]) if current_line else word
                if get_width(test_line) <= max_width:
                    current_line.append(word)
                else:
                    if not current_line:
                        lines.append(word)
                    else:
                        lines.append(' '.join(current_line))
                        current_line = [word]
            if current_line:
                lines.append(' '.join(current_line))
        return lines

    def render_editor(self, text, cursor_idx, sync_indicator, full_refresh=False):
        img = Image.new('1', (self.width, self.height), 255)
        draw = ImageDraw.Draw(img)
        
        # Insert the cursor at the correct position before wrapping so trailing spaces/cursor are handled
        text_with_cursor = text[:cursor_idx] + config.CURSOR_CHAR + text[cursor_idx:]
        
        # Wrap text by pixels using the configured maximum pixel width
        lines_to_render = self._wrap_text_pixels(text_with_cursor, self.font, config.MAX_TEXT_WIDTH)
                
        y = 10
        for line in lines_to_render[-11:]:
            draw.text((10, y), line, font=self.font, fill=0)
            y += 24
            
        # Status bar
        draw.line((0, 275, self.width, 275), fill=0)
        words_count = len(text.split())
        status_text = f"Ctrl+Q: Menu | Ctrl+S: Save ({sync_indicator}) | Words: {words_count}"
        draw.text((10, 280), status_text, font=self.status_font, fill=0)
        self.update(img, full_refresh=full_refresh)
        return img

    def update(self, img, full_refresh=False):
        if not self.epd:
            return
        try:
            if full_refresh:
                self.epd.init()
                self.epd.display(self.epd.getbuffer(img))
                self.epd.init_fast(self.epd.Seconds_1_5S)
            else:
                self.epd.display_Partial(self.epd.getbuffer(img))
        except Exception as e:
            print(f"Error updating display: {e}")

    def shutdown(self):
        if not self.epd:
            return
        print("Clearing display and putting it to sleep...")
        try:
            self.epd.init()
            self.epd.Clear()
            self.epd.sleep()
        except Exception as e:
            print(f"Error shutting down display: {e}")
